version: 2
job_defaults: &job_defaults
    docker:
        - image: circleci/openjdk:10-jdk-sid-node-browsers-legacy
    working_directory: ~/scratch

jobs:
    setup:
      <<: *job_defaults
      steps:
        - checkout
        - run: mvn dependency:go-offline
        - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}

    validation:
      <<: *job_defaults
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              - v1-dependencies-
        - run: mvn clean test
    build:
      <<: *job_defaults
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              - v1-dependencies-
        - run: mvn -B release:clean release:prepare
    deploy:
      <<: *job_defaults
      steps:
        - checkout
        - restore_cache:
        #catching all the dependencies- restore_cache:
            keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
        - run: mvn release:perform

prod_filter: &prod_filter
    filters:
        branches:
            only: release

workflows:
    version: 2
    build-and-deploy:
        jobs:
        - setup
        - validation:
            requires: 
                - setup
        - build:
            requires:
                - validation
            <<: *prod_filter
        - hold:
            type: approval
            requires: 
                - build
            <<: *prod_filter
        - deploy:
            requires: 
                - hold
            <<: *prod_filter
